---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 28568.
--- DateTime: 2024/12/3 15:30
---
local courseId=ARGV[1]
local stock =tonumber(redis.call('get', 'course:id:' .. ARGV[1]))
if (stock<=0) then
    return 1
end
redis.call('incrby','course:id:'..ARGV[1],-1)
return 0